{{- range $g := .Values.groups }}
group:  
  - groupname: {{ $g.groupname }}
    mappdSports:
      {{- range $v := $g.mappedSports }}
      - rampId: {{ $v.name }}
        sportexId: {{ $v.name }}
        category: {{ $v.name }}
      {{- end }}
{{- end }}