{{- range $group := .Values.groups }}
group:  
  - groupname: {{ $group.groupname }}
    mappdSports:
    {{- range $sport := $group.mappdSports }}
    - rampId: {{ $sport.rampId }}
      sportexId: {{ $sport.sportexId }}
      category: {{ $sport.category }}
    {{- end }}
{{- end }}
