{{- range $group := . }}
group:  
  - groupname: {{ $group.groupname }}
    mappdSports:
    {{- range .targets }}
    - rampId: {{ .rampId }}
      sportexId: {{ .sportexId }}
      category: {{ .category }}
    {{- end }}
{{- end }}
